# Generated by Django 2.0.8 on 2019-03-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='video_release_date',
        ),
    ]
