# Generated by Django 2.0.8 on 2019-03-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20190322_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Movies'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Users'),
        ),
    ]
